services:
  - type: web
    name: id-redactor-backend
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyBRCzdZzYn7q7v8I2_Z1jNn1PYATrYeoFc

  - type: web
    name: id-redactor-frontend
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_ui.py --server.port 10000
    envVars:
      - key: BACKEND_URL
        value: https://id-redactor-backend.onrender.com
