services:
  - type: web
    name: doc-masker
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr libgl1-mesa-glx poppler-utils fonts-dejavu-core
      pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run streamlit_ui.py --server.port=10000 --server.address=0.0.0.0
    plan: free
