services:
  - type: web
    name: image-redaction-service
    env: docker
    plan: free
    startCommand: ./start.sh
    envVars:
      - key: GEMINI_API_KEY
        value: your-gemini-api-key-here
    ports:
      - port: 10000  # Expose frontend port (Streamlit)
